-- DEPRECATED: This file assumed both databases on the same instance.
-- Use the instance-specific scripts instead:
--
--   MBS data (cloudos-consolidated):
--     scripts/create-readonly-role-mbs.sql
--     gcloud sql connect cloudos-consolidated --user=postgres --project=cloudos-478102 --database=clinicos_mbs
--
--   Accreditation data (clinicos-emr-pg16-staging):
--     scripts/create-readonly-role-accred.sql
--     gcloud sql connect clinicos-emr-pg16-staging --user=postgres --project=clinicos-emr-staging --database=clinicos_accreditation
