#!/bin/bash

# Development Environment Initialization Script
# Auto-generated by Claude Harness

set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

print_status() { echo -e "${GREEN}[INIT]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[WARN]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }

print_status "Initializing Python environment..."

# Create virtual environment if it doesn't exist
if [[ ! -d "venv" ]]; then
    print_status "Creating virtual environment..."
    python3 -m venv venv
fi

# Activate virtual environment
source venv/bin/activate
print_status "Virtual environment activated"

# Install dependencies
print_status "Installing dependencies..."
pip install -r requirements.txt --quiet

# Check for FastAPI/uvicorn
if grep -q "fastapi\|uvicorn" requirements.txt 2>/dev/null; then
    print_status "Starting FastAPI server..."
    uvicorn main:app --reload --port 8000 &
    echo $! > /tmp/harness-python-server.pid
    sleep 3

    # Health check
    if curl -s http://localhost:8000/health > /dev/null 2>&1 || curl -s http://localhost:8000/ > /dev/null 2>&1; then
        print_status "Server healthy at http://localhost:8000"
    else
        print_warning "Server started but health check failed - check logs"
    fi
elif grep -q "flask" requirements.txt 2>/dev/null; then
    print_status "Starting Flask server..."
    flask run --port 5000 &
    echo $! > /tmp/harness-python-server.pid
    sleep 3
    print_status "Server running at http://localhost:5000"
elif grep -q "django" requirements.txt 2>/dev/null; then
    print_status "Running Django migrations..."
    python manage.py migrate --run-syncdb 2>/dev/null || true
    print_status "Starting Django server..."
    python manage.py runserver 8000 &
    echo $! > /tmp/harness-python-server.pid
    sleep 3
    print_status "Server running at http://localhost:8000"
else
    print_status "No web framework detected - environment ready for scripts"
fi

print_status "Python environment ready!"
