#!/bin/bash

# Development Environment Shutdown Script
# Auto-generated by Claude Harness

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

print_status() { echo -e "${GREEN}[STOP]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[WARN]${NC} $1"; }

print_status "Stopping development environment..."

# Kill processes by PID files
for pidfile in /tmp/harness-*.pid; do
    if [[ -f "$pidfile" ]]; then
        pid=$(cat "$pidfile")
        if ps -p "$pid" > /dev/null 2>&1; then
            print_status "Stopping process $pid..."
            kill "$pid" 2>/dev/null || true
        fi
        rm -f "$pidfile"
    fi
done

# Kill common dev server processes
for proc in "npm run dev" "pnpm dev" "yarn dev" "next dev" "vite" "uvicorn" "flask" "nodemon"; do
    pkill -f "$proc" 2>/dev/null || true
done

# Wait a moment
sleep 1

print_status "Development environment stopped"
